name: Run my python
on:
    push:

jobs:
    build:
        name: do job1
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: run send_mail.py
          run: 
            python3 send_mail.py   
    build2:
      neam: do job2
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Run test 2 py
        run:
          pythn3 test2.py 